language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.3.4 DB=sqlite
  - DJANGO=1.3.4 DB=postgres
  - DJANGO=1.3.4 DB=mysql
  #- DJANGO=1.4.2 DB=sqlite
  #- DJANGO=1.4.2 DB=postgres
  #- DJANGO=1.4.2 DB=mysql
before_script:
  - pep8 modeltranslation
  - pyflakes modeltranslation
  - mysql -e 'create database modeltranslation;'
  - psql -c 'create database modeltranslation;' -U postgres
install:
  - pip install -q mysql-python --use-mirrors
  - pip install -q psycopg2 --use-mirrors
  - pip install -q Pillow --use-mirrors
  - pip install -q pep8 --use-mirrors
  - pip install -q pyflakes --use-mirrors
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -e . --use-mirrors
script:
  - python modeltranslation/tests/runtests.py
