language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO=1.8 DB=sqlite
  - DJANGO=1.8 DB=postgres
  - DJANGO=1.8 DB=mysql
  - DJANGO=1.9 DB=sqlite
  - DJANGO=1.9 DB=postgres
  - DJANGO=1.9 DB=mysql
  - DJANGO=1.10 DB=sqlite
  - DJANGO=1.10 DB=postgres
  - DJANGO=1.10 DB=mysql
  - DJANGO=1.11 DB=sqlite
  - DJANGO=1.11 DB=postgres
  - DJANGO=1.11 DB=mysql
matrix:
  exclude:
    - python: "3.6"
      env: DJANGO=1.8 DB=sqlite
    - python: "3.6"
      env: DJANGO=1.8 DB=mysql
    - python: "3.6"
      env: DJANGO=1.8 DB=postgres

    - python: "3.3"
      env: DJANGO=1.9 DB=sqlite
    - python: "3.3"
      env: DJANGO=1.9 DB=mysql
    - python: "3.3"
      env: DJANGO=1.9 DB=postgres
    - python: "3.6"
      env: DJANGO=1.9 DB=sqlite
    - python: "3.6"
      env: DJANGO=1.9 DB=mysql
    - python: "3.6"
      env: DJANGO=1.9 DB=postgres

    - python: "3.3"
      env: DJANGO=1.10 DB=sqlite
    - python: "3.3"
      env: DJANGO=1.10 DB=postgres
    - python: "3.3"
      env: DJANGO=1.10 DB=mysql
    - python: "3.6"
      env: DJANGO=1.10 DB=sqlite
    - python: "3.6"
      env: DJANGO=1.10 DB=postgres
    - python: "3.6"
      env: DJANGO=1.10 DB=mysql

    - python: "3.3"
      env: DJANGO=1.11 DB=sqlite
    - python: "3.3"
      env: DJANGO=1.11 DB=postgres
    - python: "3.3"
      env: DJANGO=1.11 DB=mysql
before_install:
  - pip install -q 'flake8<3'
  - PYFLAKES_NODOCTEST=1 flake8 modeltranslation
before_script:
  - mysql -e 'create database modeltranslation;'
  - psql -c 'create database modeltranslation;' -U postgres
install:
  - if [[ $DB == mysql ]] && [[ ${PYTHON:0:1} == "2" ]]; then pip install -q mysql-python; elif [[ $DB == mysql ]] && [[ ${PYTHON:0:1} == "3" ]]; then pip install -q mysqlclient; fi
  - if [[ $DB == postgres ]]; then pip install -q psycopg2; fi
  - pip install -q Pillow
  - IDJANGO=$(./travis.py $DJANGO)
  - pip install -q $IDJANGO
  - pip install -e .
  - pip install -q coveralls
script:
  - django-admin.py --version
  - coverage run --source=modeltranslation ./runtests.py
after_success:
  coveralls
